# Basics

In [1]:
# import numpy
import numpy as np

In [2]:
# returns list of the attributes and methods
# dir(np)

In [3]:
len(dir(np))

608

In [4]:
np_arr = np.arange(1000000)
py_list = list(range(1000000))

In [5]:
# time take by python list
%time for _ in range(10): [item*3 for item in py_list]

Wall time: 852 ms


In [6]:
# time take by numpy array
%time for _ in range(10): np_arr = np_arr*3

Wall time: 17 ms


# Operations

In [7]:
# len coloumns of cols must be same for all rows
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [8]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
print(type(arr1))

<class 'numpy.ndarray'>


In [10]:
arr1.shape

(2, 5)

In [11]:
arr1.dtype

dtype('int32')

In [12]:
# create 4x6 matrix filled with zeroes
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
# create 4x6 matrix filled with ones
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
# create 4x6 empty matrix - may be garbage value
np.empty((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
# m x n matrix
i = 3
j = 2
arr2 = np.zeros(shape=(i,j))

arr2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# multiplication
arr1*arr1

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [18]:
# division
arr1/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ]])

In [19]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [20]:
# power
arr1**arr1

array([[         1,          4,         27,        256,       3125],
       [     46656,     823543,   16777216,  387420489, 1410065408]],
      dtype=int32)

# Slicing

In [21]:
arr2 = np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [22]:
arr2[:]

array([1, 2, 3, 4])

In [23]:
arr2[0:]

array([1, 2, 3, 4])

In [24]:
arr2[:0]

array([], dtype=int32)

In [25]:
arr2[0:999]

array([1, 2, 3, 4])

In [26]:
arr2[999:0]

array([], dtype=int32)

In [27]:
arr2[-1:]

array([4])

In [28]:
arr2[-2:]

array([3, 4])

In [29]:
arr2[-1:2]

array([], dtype=int32)

In [30]:
arr2[-1:-2]

array([], dtype=int32)

In [31]:
# misc
temp_arr = arr2[0:2]
temp_arr

array([1, 2])

In [32]:
# it will change temp_arr & arr2
# temp_arr[1] = 99 
# print("temp_arr : ",temp_arr)
# print("arr2 : ",arr2)

In [33]:
# to avoid this
temp_arr = arr2[0:2].copy()
temp_arr[1] = 99 
print("temp_arr : ",temp_arr)
print("arr2 : ",arr2)

temp_arr :  [ 1 99]
arr2 :  [1 2 3 4]


In [34]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
# slice row 0
arr3[0]

array([1, 2, 3, 4, 5])

In [36]:
# slice col 0
arr3[:,0]

array([1, 6])

In [37]:
# slice particular element
arr3[0,3]

4

In [38]:
#[row,slice]
arr3[1,0:2]

array([6, 7])

In [39]:
#[slice,col]
arr3[0:2,2]

array([3, 8])

# Axis, Sorting & Other Functions

In [40]:
arr4 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# row wise sum
arr4.sum(axis=1)

array([ 6, 15, 24])

In [42]:
# col wise sum
arr4.sum(axis=0)

array([12, 15, 18])

In [43]:
# transpose
arr4.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
arr5 = np.array([[4,2,3],
                 [1,5,6],
                 [7,9,8]])
arr5

array([[4, 2, 3],
       [1, 5, 6],
       [7, 9, 8]])

In [45]:
# dot product for mxn and kxl -> n == k
arr4.dot(arr5)

array([[ 27,  39,  39],
       [ 63,  87,  90],
       [ 99, 135, 141]])

In [46]:
# cross product for mxn and kxl -> n == k
np.cross(arr4,arr5)

array([[  0,   9,  -6],
       [  0, -18,  15],
       [-17,   7,   7]])

In [47]:
# sorting
arr6 = np.array([[3,2,1,4],[7,6,5,8],[12,11,10,19]])

# row => axis = 1
print(np.sort(arr6,axis=1,kind='mergesort'))

# col => axis = 2
print(np.sort(arr6,axis=1,kind='quicksort'))

# default axis
print(np.sort(arr6,kind='heapsort'))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 19]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 19]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 19]]


In [48]:
# ndim => number of array dimensions
arr6.ndim

2

# Numpy Argsort, Argmin & Argmax 

In [49]:
arr7 = np.arange(8)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7])

In [50]:
# row*col = len(array)
arr7.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [51]:
# if any value is -ve, it selects the dimension automaitcally

# (-1,x) row is automatically allocated
arr7.reshape(-1,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
# (x,-1) col is automatically allocated
arr7.reshape(4,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [53]:
arr8 = np.array([4,1,5,2,7,6,3])

# Returns min value's element index
np.argmin(arr8)

1

In [54]:
# Returns max value's element index
np.argmax(arr8)

4

In [55]:
# Returns the indices that would sort an array
np.argsort(arr8)

array([1, 3, 6, 0, 2, 5, 4], dtype=int64)